// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using redb.Core.Models;

#nullable disable

namespace redb.Core.Postgres.Migrations
{
    [DbContext(typeof(RedbContext))]
    partial class RedbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            RedbBuildModel(modelBuilder);
        }

        public static void RedbBuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("global_identity")
                .StartsAt(-9223372036854769999L)
                .HasMin(-9223372036854775808L);

            modelBuilder.Entity("redb.Core.Models._RDeletedObject", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<Guid?>("CodeGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("_code_guid");

                    b.Property<long?>("CodeInt")
                        .HasColumnType("bigint")
                        .HasColumnName("_code_int");

                    b.Property<string>("CodeString")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_code_string");

                    b.Property<DateTime?>("DateBegin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_begin");

                    b.Property<DateTime?>("DateComplete")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_complete");

                    b.Property<DateTime>("DateCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_create")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_delete")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_modify")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea")
                        .HasColumnName("_hash");

                    b.Property<long>("IdOwner")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_owner");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_parent");

                    b.Property<long>("IdScheme")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_scheme");

                    b.Property<long>("IdWhoChange")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_who_change");

                    b.Property<long?>("Key")
                        .HasColumnType("bigint")
                        .HasColumnName("_key");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("_note");

                    b.Property<byte[]>("Values")
                        .HasColumnType("bytea")
                        .HasColumnName("_values");

                    b.HasKey("Id")
                        .HasName("pk__deleted_objects");

                    b.ToTable("_deleted_objects", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RDependency", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<long?>("IdScheme1")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_scheme_1");

                    b.Property<long>("IdScheme2")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_scheme_2");

                    b.HasKey("Id")
                        .HasName("pk__dependencies");

                    b.HasIndex(new[] { "IdScheme1" }, "IX__dependencies__schemes_1")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdScheme2" }, "IX__dependencies__schemes_2")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdScheme1", "IdScheme2" }, "ix__dependencies")
                        .IsUnique();

                    b.ToTable("_dependencies", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RFunction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("_body");

                    b.Property<long>("IdScheme")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_scheme");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("_language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("_name");

                    b.HasKey("Id")
                        .HasName("pk__functions");

                    b.HasIndex(new[] { "IdScheme" }, "IX__functions__schemes")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdScheme", "Name" }, "ix__functions_scheme_name")
                        .IsUnique();

                    b.ToTable("_functions", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RLink", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<long>("Id1")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_1");

                    b.Property<long>("Id2")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_2");

                    b.HasKey("Id")
                        .HasName("pk__links");

                    b.HasIndex(new[] { "Id1", "Id2" }, "ix__links")
                        .IsUnique();

                    b.ToTable("_links", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RList", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<string>("Alias")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_alias");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.HasKey("Id")
                        .HasName("pk__lists");

                    b.ToTable("_lists", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RListItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<long>("IdList")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_list");

                    b.Property<long?>("IdObject")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_object");

                    b.Property<string>("_RValue")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_value");

                    b.HasKey("Id")
                        .HasName("pk__list_items");

                    b.HasIndex(new[] { "IdList" }, "IX__list_items__id_list")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdObject" }, "IX__list_items__objects")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("_list_items", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RObject", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<Guid?>("CodeGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("_code_guid");

                    b.Property<long?>("CodeInt")
                        .HasColumnType("bigint")
                        .HasColumnName("_code_int");

                    b.Property<string>("CodeString")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_code_string");

                    b.Property<DateTime?>("DateBegin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_begin");

                    b.Property<DateTime?>("DateComplete")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_complete");

                    b.Property<DateTime>("DateCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_create")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_modify")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea")
                        .HasColumnName("_hash");

                    b.Property<long>("IdOwner")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_owner");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_parent");

                    b.Property<long>("IdScheme")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_scheme");

                    b.Property<long>("IdWhoChange")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_who_change");

                    b.Property<long?>("Key")
                        .HasColumnType("bigint")
                        .HasColumnName("_key");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("_note");

                    b.HasKey("Id")
                        .HasName("pk__objects");

                    b.HasIndex(new[] { "CodeGuid" }, "IX__objects__code_guid")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CodeInt" }, "IX__objects__code_int")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "CodeString" }, "IX__objects__code_string")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "DateCreate" }, "IX__objects__date_create")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "DateModify" }, "IX__objects__date_modify")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Hash" }, "IX__objects__hash")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Name" }, "IX__objects__name")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdParent" }, "IX__objects__objects")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdScheme" }, "IX__objects__schemes")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdOwner" }, "IX__objects__users1")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdWhoChange" }, "IX__objects__users2")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("_objects", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RPermission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<bool?>("Delete")
                        .HasColumnType("boolean")
                        .HasColumnName("_delete");

                    b.Property<long>("IdRef")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_ref");

                    b.Property<long?>("IdRole")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_role");

                    b.Property<long?>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_user");

                    b.Property<bool?>("Insert")
                        .HasColumnType("boolean")
                        .HasColumnName("_insert");

                    b.Property<bool?>("Select")
                        .HasColumnType("boolean")
                        .HasColumnName("_select");

                    b.Property<bool?>("Update")
                        .HasColumnType("boolean")
                        .HasColumnName("_update");

                    b.HasKey("Id")
                        .HasName("pk__object_permissions");

                    b.HasIndex(new[] { "IdRole" }, "IX__permissions__roles")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdUser" }, "IX__permissions__users")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdRole", "IdUser", "IdRef", "Select", "Insert", "Update", "Delete" }, "ix__permissions")
                        .IsUnique();

                    b.ToTable("_permissions", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RRole", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.HasKey("Id")
                        .HasName("pk__roles");

                    b.HasIndex(new[] { "Name" }, "ix__roles")
                        .IsUnique();

                    b.ToTable("_roles", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RScheme", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<string>("Alias")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_alias");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_parent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.Property<string>("NameSpace")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("_name_space");

                    b.HasKey("Id")
                        .HasName("pk__schemes");

                    b.HasIndex(new[] { "IdParent" }, "IX__schemes__schemes")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Name" }, "ix__schemes")
                        .IsUnique();

                    b.ToTable("_schemes", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RStructure", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<string>("Alias")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_alias");

                    b.Property<bool?>("AllowNotNull")
                        .HasColumnType("boolean")
                        .HasColumnName("_allow_not_null");

                    b.Property<string>("DefaultEditor")
                        .HasColumnType("text")
                        .HasColumnName("_default_editor");

                    b.Property<byte[]>("DefaultValue")
                        .HasColumnType("bytea")
                        .HasColumnName("_default_value");

                    b.Property<long?>("IdList")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_list");

                    b.Property<long?>("IdOverride")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_override");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_parent");

                    b.Property<long>("IdScheme")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_scheme");

                    b.Property<long>("IdType")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_type");

                    b.Property<bool?>("IsArray")
                        .HasColumnType("boolean")
                        .HasColumnName("_is_array");

                    b.Property<bool?>("IsCompress")
                        .HasColumnType("boolean")
                        .HasColumnName("_is_compress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.Property<long?>("Order")
                        .HasColumnType("bigint")
                        .HasColumnName("_order");

                    b.Property<bool?>("Readonly")
                        .HasColumnType("boolean")
                        .HasColumnName("_readonly");

                    b.Property<bool?>("StoreNull")
                        .HasColumnType("boolean")
                        .HasColumnName("_store_null");

                    b.HasKey("Id")
                        .HasName("pk__structure");

                    b.HasIndex(new[] { "IdList" }, "IX__structures__lists")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdScheme" }, "IX__structures__schemes")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdParent" }, "IX__structures__structures")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdType" }, "IX__structures__types")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdScheme", "Name" }, "ix__structures")
                        .IsUnique();

                    b.ToTable("_structures", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<string>("DbType")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_db_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.Property<string>("Type1")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_type");

                    b.HasKey("Id")
                        .HasName("pk__types");

                    b.ToTable("_types", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<DateTime?>("DateDismiss")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_dismiss");

                    b.Property<DateTime>("DateRegister")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_date_register")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_email");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("_enabled");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("_password");

                    b.Property<string>("Phone")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("_phone");

                    b.HasKey("Id")
                        .HasName("pk__users");

                    b.ToTable("_users", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RUsersRole", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<long>("IdRole")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_role");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_user");

                    b.HasKey("Id")
                        .HasName("pk__users_roles");

                    b.HasIndex(new[] { "IdRole" }, "IX__users_roles__roles")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdUser" }, "IX__users_roles__users")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdRole", "IdUser" }, "ix__users_roles")
                        .IsUnique();

                    b.ToTable("_users_roles", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RValue", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("_id");

                    b.Property<bool?>("Boolean")
                        .HasColumnType("boolean")
                        .HasColumnName("_boolean");

                    b.Property<double?>("Double")
                        .HasColumnType("double precision")
                        .HasColumnName("_double");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("_guid");

                    b.Property<long>("IdObject")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_object");

                    b.Property<long>("IdStructure")
                        .HasColumnType("bigint")
                        .HasColumnName("_id_structure");

                    b.Property<long?>("Long")
                        .HasColumnType("bigint")
                        .HasColumnName("_long");

                    b.Property<string>("String")
                        .HasMaxLength(850)
                        .HasColumnType("character varying(850)")
                        .HasColumnName("_string");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("_text");

                    b.Property<byte[]>("ByteArray")
                        .HasColumnType("bytea")
                        .HasColumnName("_bytearray");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("_datetime");

                    b.HasKey("Id")
                        .HasName("pk__values");

                    b.HasIndex(new[] { "Boolean" }, "IX__values__Boolean")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "DateTime" }, "IX__values__DateTime")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Double" }, "IX__values__Double")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Guid" }, "IX__values__Guid")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "Long" }, "IX__values__Long")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "String" }, "IX__values__String")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdObject" }, "IX__values__objects")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdStructure" }, "IX__values__structures")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.HasIndex(new[] { "IdStructure", "IdObject" }, "ix__values_so")
                        .IsUnique();

                    b.ToTable("_values", (string)null);
                });

            modelBuilder.Entity("redb.Core.Models._RDependency", b =>
                {
                    b.HasOne("redb.Core.Models._RScheme", "Scheme1Navigation")
                        .WithMany("DependencyScheme1Navigations")
                        .HasForeignKey("IdScheme1")
                        .HasConstraintName("fk__dependencies__schemes_1");

                    b.HasOne("redb.Core.Models._RScheme", "Scheme2Navigation")
                        .WithMany("DependencyScheme2Navigations")
                        .HasForeignKey("IdScheme2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__dependencies__schemes_2");

                    b.Navigation("Scheme1Navigation");

                    b.Navigation("Scheme2Navigation");
                });

            modelBuilder.Entity("redb.Core.Models._RFunction", b =>
                {
                    b.HasOne("redb.Core.Models._RScheme", "SchemeNavigation")
                        .WithMany("Functions")
                        .HasForeignKey("IdScheme")
                        .IsRequired()
                        .HasConstraintName("fk__functions__schemes");

                    b.Navigation("SchemeNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RListItem", b =>
                {
                    b.HasOne("redb.Core.Models._RList", "ListNavigation")
                        .WithMany("ListItems")
                        .HasForeignKey("IdList")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__list_items__id_list");

                    b.HasOne("redb.Core.Models._RObject", "ObjectNavigation")
                        .WithMany("ListItems")
                        .HasForeignKey("IdObject")
                        .HasConstraintName("fk__list_items__objects");

                    b.Navigation("ListNavigation");

                    b.Navigation("ObjectNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RObject", b =>
                {
                    b.HasOne("redb.Core.Models._RUser", "OwnerNavigation")
                        .WithMany("ObjectOwnerNavigations")
                        .HasForeignKey("IdOwner")
                        .IsRequired()
                        .HasConstraintName("fk__objects__users1");

                    b.HasOne("redb.Core.Models._RObject", "ParentNavigation")
                        .WithMany("InverseParentNavigation")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk__objects__objects");

                    b.HasOne("redb.Core.Models._RScheme", "SchemeNavigation")
                        .WithMany("Objects")
                        .HasForeignKey("IdScheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__objects__schemes");

                    b.HasOne("redb.Core.Models._RUser", "WhoChangeNavigation")
                        .WithMany("ObjectWhoChangeNavigations")
                        .HasForeignKey("IdWhoChange")
                        .IsRequired()
                        .HasConstraintName("fk__objects__users2");

                    b.Navigation("OwnerNavigation");

                    b.Navigation("ParentNavigation");

                    b.Navigation("SchemeNavigation");

                    b.Navigation("WhoChangeNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RPermission", b =>
                {
                    b.HasOne("redb.Core.Models._RRole", "RoleNavigation")
                        .WithMany("Permissions")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk__permissions__roles");

                    b.HasOne("redb.Core.Models._RUser", "UserNavigation")
                        .WithMany("Permissions")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk__permissions__users");

                    b.Navigation("RoleNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RScheme", b =>
                {
                    b.HasOne("redb.Core.Models._RScheme", "ParentNavigation")
                        .WithMany("InverseParentNavigation")
                        .HasForeignKey("IdParent")
                        .HasConstraintName("fk__schemes__schemes");

                    b.Navigation("ParentNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RStructure", b =>
                {
                    b.HasOne("redb.Core.Models._RList", "ListNavigation")
                        .WithMany("Structures")
                        .HasForeignKey("IdList")
                        .HasConstraintName("fk__structures__lists");

                    b.HasOne("redb.Core.Models._RStructure", "ParentNavigation")
                        .WithMany("InverseParentNavigation")
                        .HasForeignKey("IdParent")
                        .HasConstraintName("fk__structures__structures");

                    b.HasOne("redb.Core.Models._RScheme", "SchemeNavigation")
                        .WithMany("Structures")
                        .HasForeignKey("IdScheme")
                        .IsRequired()
                        .HasConstraintName("fk__structures__schemes");

                    b.HasOne("redb.Core.Models._RType", "TypeNavigation")
                        .WithMany("Structures")
                        .HasForeignKey("IdType")
                        .IsRequired()
                        .HasConstraintName("fk__structures__types");

                    b.Navigation("ListNavigation");

                    b.Navigation("ParentNavigation");

                    b.Navigation("SchemeNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RUsersRole", b =>
                {
                    b.HasOne("redb.Core.Models._RRole", "RoleNavigation")
                        .WithMany("UsersRoles")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__users_roles__roles");

                    b.HasOne("redb.Core.Models._RUser", "UserNavigation")
                        .WithMany("UsersRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__users_roles__users");

                    b.Navigation("RoleNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RValue", b =>
                {
                    b.HasOne("redb.Core.Models._RObject", "ObjectNavigation")
                        .WithMany("Values")
                        .HasForeignKey("IdObject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__values__objects");

                    b.HasOne("redb.Core.Models._RStructure", "StructureNavigation")
                        .WithMany("Values")
                        .HasForeignKey("IdStructure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk__values__structures");

                    b.Navigation("ObjectNavigation");

                    b.Navigation("StructureNavigation");
                });

            modelBuilder.Entity("redb.Core.Models._RList", b =>
                {
                    b.Navigation("ListItems");

                    b.Navigation("Structures");
                });

            modelBuilder.Entity("redb.Core.Models._RObject", b =>
                {
                    b.Navigation("InverseParentNavigation");

                    b.Navigation("ListItems");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("redb.Core.Models._RRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("redb.Core.Models._RScheme", b =>
                {
                    b.Navigation("DependencyScheme1Navigations");

                    b.Navigation("DependencyScheme2Navigations");

                    b.Navigation("Functions");

                    b.Navigation("InverseParentNavigation");

                    b.Navigation("Objects");

                    b.Navigation("Structures");
                });

            modelBuilder.Entity("redb.Core.Models._RStructure", b =>
                {
                    b.Navigation("InverseParentNavigation");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("redb.Core.Models._RType", b =>
                {
                    b.Navigation("Structures");
                });

            modelBuilder.Entity("redb.Core.Models._RUser", b =>
                {
                    b.Navigation("ObjectOwnerNavigations");

                    b.Navigation("ObjectWhoChangeNavigations");

                    b.Navigation("Permissions");

                    b.Navigation("UsersRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
